# Generated by Django 5.2.3 on 2025-06-12 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty', models.CharField(max_length=100)),
                ('checked', models.BooleanField(default=False)),
                ('item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('receivable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('final_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_meta', to='core.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to='core.sheet')),
            ],
        ),
    ]
