# Generated by Django 5.2.3 on 2025-06-12 17:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='invoicemeta',
            name='final_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicemeta',
            name='receivable',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicemeta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
