# Generated by Django 5.2.3 on 2025-06-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sheet_options_alter_invoicemeta_final_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoicemeta',
            name='note',
            field=models.TextField(default="Please make sure you have received boxes for new items, we won't be responsible for your boxes after 7 days."),
        ),
        migrations.AddField(
            model_name='invoicemeta',
            name='terms',
            field=models.TextField(default='Only --- Days Warranty\nNo Burn and Damage Warranty\nNo Replacement after Warranty Time\nNo warranty for "artifacts", "No display", "Burn", "Damage" for Used GPUs\nI.W / INT = international warranty...No responsibility of the Seller(Games and Geeks)\nNo warranty for Mined(used in Crypto Mining) GPUs etc\nLLW = Limited Local Warranty = 1year Free + 1year/2year Paid warranty'),
        ),
        migrations.AddField(
            model_name='invoicemeta',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.customer'),
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
